# language target
language: cpp
compiler: gcc

# main build matrix
matrix:
  include:
    - name: "Bionic Ubuntu Linux"
      os: linux
      dist: bionic
      sudo: required
      env: TARGETOS=bionic-linux

# install dependencies (for now ubuntu only)
install:
  - sudo apt update
  - sudo apt install ffmpeg sox mplayer libnotify-dev qt5-default qt5-qmake g++ make

# build & test scripts
script:
  - make clean
  - qmake mystiq.pro
  - cat Makefile
  - make

# notifications (only via telegram)
notifications:
  email: true
  #webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# no deploy section for now.
