# language target
language: cpp
compiler: gcc

# main build matrix
matrix:
  include:
    - name: "Bionic Ubuntu Linux"
      os: linux
      dist: bionic
      sudo: required
      env: TARGETOS=bionic-linux

# install, install QT5.12.3 from ppa
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-bionic
  - sudo apt update
  - sudo apt install build-essential g++ make ffmpeg sox mplayer libnotify-dev mesa-common-dev libglvnd-dev
  - sudo apt install qt-latest tree
  - echo "/opt/qt512/bin" | sudo tee /etc/xdg/qtchooser/default.conf
  - echo "/opt/qt512/lib" | sudo tee -a /etc/xdg/qtchooser/default.conf
  - qtchooser -print-env
  - qmake -v

# build & test scripts
script:
  - qmake mystiq.pro
  - make
  - sudo make install

# success, prepare the appimage build
after_script:
  # install deps
  - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - chmod +x linuxdeploy-x86_64.AppImage
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod +x appimagetool-x86_64.AppImage
  # build the AppDir
  - make install INSTALL_ROOT=AppDir
  # add extra tools
  - prepare-AppDir.sh
  # run the linuxdeploy script
  - ./linuxdeploy-x86_64.AppImage --appdir=AppDir
  # create the AppImage file
  - ./appimagetool-x86_64.AppImage AppDir
  # list the contents
  - ls -lh

# notifications (only via telegram)
notifications:
  email: true
  #webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# no deploy section for now.
