# language target
language: cpp
compiler: gcc

# main build matrix
matrix:
  include:
    - name: "Bionic Ubuntu Linux"
      os: linux
      dist: bionic
      sudo: required
      env: TARGETOS=bionic-linux

# before install, install QT5.10+
before_install:
  - wget http://download.qt.io/official_releases/qt/5.13/5.13.2/qt-opensource-linux-x64-5.13.2.run
  - chmod +x qt-opensource-linux-x64-5.13.2.run
  - sudo ./qt-opensource-linux-x64-5.13.2.run
  - cat /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf
  - qtchooser -print-env
  - qmake -v

# install dependencies (for now ubuntu only)
install:
  - sudo apt install ffmpeg sox mplayer libnotify-dev g++ make

# build & test scripts
script:
  - make clean
  - qmake mystiq.pro
  - make

# notifications (only via telegram)
notifications:
  email: true
  #webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# no deploy section for now.
